# Generated by Django 5.0 on 2024-01-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.instructor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='usuarios',
            field=models.ManyToManyField(to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.clase'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='tipo_clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.tipoclase'),
        ),
    ]
